server:
  port: 7888
spring:
  application:
    name: producer
  cloud:
    stream:
      #      default:
      #        binder: kafka
      #        producer:
      #          #为了兼容非java端消费消息，使用原生encoding，不会有content-type头信息在消息体中，bytearray序列化，消费端直接获取原始字符串自己处理。
      #          useNativeEncoding: true
      kafka:
        binder:
          #Kafka的消息中间件服务器
          brokers: 192.168.110.130:9092
          #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          #          auto-create-topics: true
          auto-add-partitions: true
          min-partition-count: 1
      bindings:
        #这里用stream给我们提供的默认output，后面会讲到自定义output
        output:
          #消息发往的目的地(主题)
          destination: stream-demo
          producer:
            # 使用id作为分区号
            partitionKeyExpression: payload.id